version: '3.9'

services:
  api-gateway:
    build:
      context: ./apiGateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - reservation-service
      - room-service

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "50051:50051"

  reservation-service:
    build:
      context: ./reservation-service
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    depends_on:
      - kafka

  room-service:
    build:
      context: ./room-service
      dockerfile: Dockerfile
    ports:
      - "50053:50053"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    command:
      - "/bin/bash"
      - "-c"
      - "while ! nc -z zookeeper 2181; do sleep 1; done; /etc/confluent/docker/run"

  kafka-consumer:
    build:
      context: ./kafka
      dockerfile: Dockerfile
    depends_on:
      - kafka
    restart: always

networks:
  default:
    driver: bridge
  my-network: # Nouveau réseau personnalisé
    driver: bridge
